all:
  children:
    managed:
      children:
        docker_hosts:
        singular_hosts:

    docker_hosts:
      hosts:
        matrix-1:
          ansible_host: 10.67.30.24
          mac: bc:24:11:2d:5a:9d
        newt-1:
          ansible_host: 10.67.30.25
          mac: bc:24:11:7c:61:ed
        appstack-1:
          ansible_host: 10.67.10.25
          mac: bc:24:11:0e:f4:00
        arrstack-1:
          ansible_host: 10.67.10.26
          mac: bc:24:11:b9:ef:07
        devstack-1:
          ansible_host: 10.67.10.31
          mac: bc:24:11:c3:cc:26
        infstack-1:
          ansible_host: 10.67.40.25
          mac: bc:24:11:39:45:9e
        mediastack-1:
          ansible_host: 10.67.10.27
          mac: bc:24:11:31:be:43
        pangolin-1:
          ansible_host: 89.127.232.7
        nextcloud-1:
          ansible_host: 10.67.10.29
          mac: bc:24:11:96:71:59
        monitoring-1:
          ansible_host: 10.67.40.27
          mac: bc:24:11:61:f7:eb
          monitoring_core: true
        kasm-1:
          ansible_host: 10.67.10.28
          mac: bc:24:11:fe:d2:0b

    core_infra:
      hosts:
        arasaka-1:
          ansible_host: 10.67.45.27
          mac: bc:30:5b:ed:68:5d
        datafortress-1:
          ansible_host: 10.67.20.24
          mac: ec:f4:bb:c7:0c:c0

    network_devices:
      children:
        routeros_switches:
          hosts:
            gridlink-1:
              ansible_host: 10.67.45.2
        opnsense_firewalls:
          hosts:
            opensense-1:
              ansible_host: 10.67.45.1
