docker_prep_enabled: true

docker_agent_name: docker-agent
docker_agent_uid: 1101
docker_agent_gid: 1101
docker_agent_home: /var/lib/docker-agent
docker_agent_shell: /usr/sbin/nologin

docker_service_name: docker

deploy_root: "/etc/komodo"
ssh_root: "{{ deploy_root }}/ssh"
compose_repo_root: "{{ deploy_root }}/repos"
compose_git_base_url: "ssh://git@gitlab-ssh.eddiequinn.casa:2424/compose-files"
infisical_domain: "https://infisical.eddiequinn.casa/api"

# Komodo Vars

# Monitoring stack vars

# Docker package management is enabled so fresh Docker hosts can bootstrap cleanly
docker_manage_packages: true

# Cloudflare Utils vars

# Renovate vars
