---
# Shared defaults for all Ansible-managed network devices
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: community.routeros.routeros
ansible_user: admin
ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
